### ISSUE TITLE
线程池如何关闭的？

### ISSUE THREAD

**Issue by KupoGu** [continew-org/continew-starter#1]
### Bug 描述

声明线程池配置后，程序关闭没有看到有结束线程池的地方呢

### 复现步骤

声明线程池配置后，程序关闭没有看到有结束线程池的地方呢

### 预期结果

是不是要配置个bean自动结束掉

### 环境信息

jdk 21 ,starter-最新版本

### 确认

- [X] 阅读文档
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
可以在配置 Bean 销毁时（ `@PreDestroy`）关闭，有兴趣提交一个 PR 吗？

**Comment by Charles7c** [comment]
https://github.com/Charles7c/continew-starter/commit/c4051a6465e0d70d119ec27c6ae4eb4d1893339a
