### ISSUE TITLE
群链接失效了

### ISSUE THREAD

**Issue by yeora26** [continew-org/continew-starter#3]
### Bug 描述

readme群链接失效

### 复现步骤

点击群链接

### 预期结果

正常访问

### 环境信息

![截图 2024-05-22 10-53-45](https://github.com/Charles7c/continew-starter/assets/111340195/bd53d0a4-458f-4b52-bc74-5b8cc4ab9f83)

### 确认

- [X] 阅读文档
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
感谢反馈，确实刚发现这个事。
<img src="https://continew.top/qrcode.jpg" width="200px" height="200px" />
