### ISSUE TITLE
发送邮件无法自定义发件人昵称

### ISSUE THREAD

**Issue by iNuoers** [continew-org/continew-starter#5]
### Feature 描述

希望发送邮件支持自定义发件人昵称的功能

### 描述一下您想要的解决方案

messageHelper.setFrom(nick+" <"+mailSender.getUsername()+">"); 

### 确认

- [X] 阅读文档
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
可以，等 2.1.1 发布支持
