### ISSUE TITLE
希望RedisUtils加入zset相关操作

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-starter#6]
### Feature 描述

希望在RedisUtils中加入以下zset相关操作：
添加元素到zset中，并指定分数。
从zset中删除指定元素。
获取zset中元素的分数。
根据分数范围获取zset中的元素列表。
获取zset中元素的排名。
获取zset中元素的个数。
计算zset中多个元素的分数之和。
通过这些操作的加入，RedisUtils将更加完善，能够满足项目中对有序集合的各种需求，进一步提高我们的开发效率。我们期待RedisUtils在未来的版本中不断完善，为项目带来更多的便利。

### 描述一下您想要的解决方案

无

### 确认

- [X] 阅读文档
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
已添加至 2.7.3 版本。https://github.com/continew-org/continew-starter/commit/56edceec7e7c61bbd06a1995c2351441302ac969
