### ISSUE TITLE
PageResp Page

### ISSUE THREAD

**Issue by AI2Hub** [continew-org/continew-starter#7]
### Bug 描述

continew-starter-extension/continew-starter-extension-crud/continew-starter-extension-crud-mf/src/main/java/top/continew/starter/extension/crud/model/resp)
/PageResp.java

 public static <L> PageResp<L> build(int page, int size, List<L> list) 
this method
int toIndex = page * size + fromIndex.  There seems to be a problem.
toIndex  normal is  fromIndex + size，It's not  page * size + fromIndex

### 复现步骤

21 pieces of data, each page 10 pieces. 
Paging is switched repeatedly. 
The 2 page can be reproduced. There is only 1 piece of data on this page

### 预期结果

The second page is 10 pieces of data, not only one.

### 环境信息

2.7.4

### 额外补充

this is fix code:

public static <L> PageResp<L> build(int page, int size, List<L> list) {
    if (CollUtil.isEmpty(list)) {
        return empty(); 
    }

    PageResp<L> pageResp = new PageResp<>();
    pageResp.setTotal(list.size()); 

    int fromIndex = (page - 1) * size;
    int toIndex = Math.min(fromIndex + size, list.size());

    if (fromIndex >= list.size()) {
        pageResp.setList(new ArrayList<>(0));
    } else {
        pageResp.setList(list.subList(fromIndex, toIndex));
    }
    return pageResp;
}

### 确认

- [X] 阅读文档
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by zaiYe** [comment]
作者解决一下啊，低级错误

**Comment by Charles7c** [comment]
有时间欢迎提个 PR，才看到这边还有提 issue。

**Comment by Charles7c** [comment]
将于 v2.8.0 发布。
